// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etwbofsmxyxuayrhdxen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0d2JvZnNteHl4dWF5cmhkeGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODY2NTMsImV4cCI6MjA2NDk2MjY1M30.HvOQLxjCRf7xyQsMOCLYYBXmhaF6pwQUcwOQLxbwwLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);